#!/bin/bash

set -o vi
shopt -u cmdhist

export PS1="\u@\h \[\e[32;1m\]\w\[\e[m\] \$ "

alias f='find'
alias l='ls -alhtr'
alias ll='l'
alias grep='grep --color=auto'
alias grepr='grep -rn'
alias less='less --chop-long-lines'
alias paug='ps aux | grep'
alias listening='netstat -a -n | grep LISTEN'
alias vi=vim
alias e=vim
alias pd='pushd'
alias pp='popd'

vim_plugins_inst() {
    vim +PluginInstall +qall
}

refactor() {
    for f in $(find . -type f); do
        if grep -q "$1" "$f"; then
            sed -i -e "s/${1}/${2}/g" "$f"
        fi
        # TODO // Rename files ($1.java -> $2.java)
    done;
}
