#!/bin/bash
set -o vi
shopt -u cmdhist

export PS1="\u@\h \[\e[32;1m\]\w\[\e[m\] \$ "

alias f='find'
alias l='ls -alh'
alias ll='l'
alias grep='grep --color=auto'
alias grepr='grep -rn'
alias less='less --chop-long-lines'
alias paug='ps aux | grep'
alias listening='netstat -a -n | grep LISTEN'
alias vi=vim
alias e=vim

vim_plugins_inst() {
    vim +PluginInstall +qall
}
