#!/bin/bash
export CLICOLOR=1
export LSCOLORS=dxfxcxdxbxegedabagacad
export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$HOME/bin/apache-ant-1.9.4/bin:$PATH
export PATH=$HOME/bin/apache-maven-3.3.3/bin:$PATH
export PATH=$HOME/bin/gradle-2.4/bin:$PATH
