#!/bin/bash
export GIT_AUTHOR_NAME="Dmitry Minkovsky"
export GIT_AUTHOR_EMAIL="dminkovsky@gmail.com"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"

if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
  . /usr/local/etc/bash_completion.d/git-completion.bash
fi

alias ga='git add'
alias gap='ga -p'
alias gau='ga -u'
alias gc='git commit'
alias gcm='gc -m'
alias gca='gc --amend'
alias gcam='gca --no-edit'
alias g='git status'
alias gd='git diff --color=always'
alias gds='gd --stat'
alias gdc='gd --cached'
alias gl='git log --abbrev-commit --oneline'
alias glf='gl --follow'
alias glg='gl --graph --oneline --abbrev'
alias glh='gl | head -8'
alias gb='git branch'
alias gs='git show'
alias gss='gs --stat'
alias gsb='git show-branch'
alias gr='git rebase'
alias gri='gr -i'
alias grc='gr --continue'

alias list='git stash list'
alias stash='git stash save'
alias pop='git stash pop'

git config --global color.ui true
# https://superuser.com/a/1202694/80826
# and https://stackoverflow.com/a/18781512/741970
git config --global core.pager 'less -r -+F -+X'
